print("v1.5")
name = input("Назовите своего ассистента: ")
print(f"Привет, меня зовут {name}. Я твой личный ассистент.\n")
username = input("Давай познакомимся! Как тебя зовут?\nТвое имя: ")
print(f"\nОтлично, {username}! Чем могу помочь?")
user_answer = input()